os:
  - linux
language: node_js
node_js:
 - "11.0.0"
addons:
 apt:
   sources:
     - google-chrome
   packages:
     - google-chrome-stable
dist: trusty
sudo: false

branches:
  only:
  - develop

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - rm -rf package-lock.json
  - npm i -g yarn
  - npm i -g @angular/cli
  - yarn install --silent --no-progress

script:
  - yarn lint
  - yarn test --watch=false --progress=true
  - yarn build --base-href https://github.com/fedoretsElena/study-app/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/study-app-en
  on:
    branch: develop
