os:
  - linux
language: node_js
node_js:
 - "11.0.0"
dist: trusty
sudo: false

branches:
  only:
  - develop

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - npm i -g @angular/cli
  - yarn i --silent --no-progress

script:
  - yarn lint
  - yarn test
  - yarn build --base-href https://github.com/fedoretsElena/study-app/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/study-app-en
  on:
    branch: develop
